version: "3"
services:
  app:
    image: arjun4936/note-taker-nodejs:latest
    container_name: note-taker
    env_file:
      - /home/ubuntu/envs/note-taker.env
    ports:
      - "3000:3000"
    restart: always
